### ISSUE TITLE
Come up with a few color palettes

### ISSUE THREAD

**Issue by line47** [18F/uswds-jekyll#122]
Create a custom color palette utilizing the following components.
Preview of some random colors to start https://federalist-proxy.app.cloud.gov/preview/18f/uswds-jekyll/sw-color-palette/

- Header
- USA banner
- Top navigation
- Side navigation
- Primary footer bar
- Footer
- Hero
- Buttons
- Links
- Alt color section (usa-dark-bg)

Edit: three examples:
https://federalist-proxy.app.cloud.gov/site/18f/uswds-jekyll/
https://federalist-proxy.app.cloud.gov/preview/18f/uswds-jekyll/sw-beach/
https://federalist-proxy.app.cloud.gov/preview/18f/federalist-uswds-template/palette-experiments/

**Comment by line47** [comment]
☝️ @ericronne @AvivaOskow

**Comment by wslack** [comment]
Moved to Ready, can be "in progress" when you're working on it.

**Comment by AvivaOskow** [comment]
@wslack @austinhernandez 

**Update on work here:**
(Aviva)
- Used the new USWDS color range to select 16+ color palette combinations to try
- Narrowed down to 10, some with variants for header/footer choice, etc.
- Added range of images related to different agencies/general American stuff to help with look and feel definition for each

**TO DO (Austin + Aviva)**
- Narrow down options further
- Add visual look/feel/mood descriptors to each (already started) and name themes

**TO DO (Austin, Aviva rolls off)**
- Make a delivery plan for devs
- Make sure themes account for the components listed in original issue
- [ ] - header
- [ ] - USA banner
- [ ] - Top navigation
- [ ] - Side navigation
- [ ] - Primary footer bar
- [ ] - Footer
- [ ] - Hero
- [ ] - Buttons
- [ ] - Links
- [ ] - Alt color section (usa-dark-bg)
- Figure out how these are different than the template? They should be able to apply to them?
- Give access to themes to USWDS team for best practices sharing

**Comment by wslack** [comment]
AWESOME @AvivaOskow this answers all of my questions this evening!

**Comment by austinhernandez** [comment]
Today, I wrapped up work on new theme colors. While trying to figure out how to frame how users would choose a theme. This will help me determine what information needs to be when I create deliverables: _As a designer, I need to be able to pick a template or theme that addresses my agency and my agency's user's goals._

## Preface text
Just as [our written tone adapts to our users’ feelings](https://content-guide.18f.gov/voice-and-tone/#choosing-a-tone), **the look and feel of your website should adapt to the site’s topic and content.**

The following templates will provide examples of how to choose a theme that works for your agency and audience.

## Example text
_Scenario:_ Gael is a technology contractor for the Department of Homeland Security. He's is in charge of selecting a theme for a roll out of the new National Terrorism Advisory System website. He finds a list of themes for an easy deploy site on Federalist and notices there's an orange theme. Since orange is his favorite color he selects this theme along with it's accompanying imagery. 

* Avoid: In this example, the bright colors and imagery do not match the content of terrorist threat. 
![what not to do](https://user-images.githubusercontent.com/23194720/38057284-e0ea6a24-32ac-11e8-853b-944892071534.png)

* Suggestion for your content: In this example, the imagery is of an American flag with dark colors make the site feel more serious. 
![suggestion](https://user-images.githubusercontent.com/23194720/38057283-e0da8e56-32ac-11e8-9031-93726354dbe8.png)

---

As you can see, on first glance the design of the site does not match something as important and serious as a terrorist threat. 

Here's a better use of the orange theme for the USDA's Urban Gardening division!
![better use of theme](https://user-images.githubusercontent.com/23194720/38057282-e0cc4008-32ac-11e8-9bf7-a6541ba4d2b3.png)

I'd love quick (< 30mins) design feedback on this direction from @AvivaOskow and design / content feedback from @kategarklavs and/or @thebestsophist.

**Comment by kategarklavs** [comment]
Yo hey! Happy to review the content. My plan is to 1) copy the content (as is) into a Google doc; 2) make changes in Suggesting mode so you all can accept/reject as you see fit; 3) share the link here. More soon 👍

**Comment by kategarklavs** [comment]
Hey all! Here are some super-quick edits:

https://docs.google.com/document/d/1j1cD86_8Y3-e3pT1kJ3mMWjgL3iDCwP4jAPZlnq-KM4/edit?usp=sharing

lmk if you have any questions/thoughts/comments 👍

**Comment by ericronne** [comment]
I think this could be super educational and helpful for federalist customers. Great stuff @austinhernandez!

Two quick thoughts …

- Is _designer_ the best description for the user, or would the target be a comms person such as the famous **[Chris the Communicator](https://docs.google.com/document/d/1Sf5ie1eUqsiqQbZAjgpFPfnbr5ZfTXWSGqm4QktOsG4/edit#)**?
- I wonder if we should have more generic ("faker") content for the examples. Might be over-thinking it, but i wouldn't want to rustle any NTAS feathers, e.g.

**Comment by austinhernandez** [comment]
Thanks @kategarklavs for the edits! All of the stock photos, the WDS palette intro content are on the drive: https://drive.google.com/open?id=1WjjCtGqS_9_yTA83oPCPQPpmVpeA802Z

**Comment by wslack** [comment]
> I wonder if we should have more generic ("faker") content for the examples. Might be over-thinking it, but i wouldn't want to rustle any NTAS feathers, e.g.

Just adding to this, its totally ok with me for the templates to have Lorem Ipsum content - part of the utility of the different palettes is showing how Federalist prototyping allows people to see multiple possible "looks" for the same site content.

If the versions do have unique content, it should be nonsense content.

Also, just like https://federalist-proxy.app.cloud.gov/preview/18f/uswds-jekyll/sw-color-palette/ from Scott's original post, each of the palettes should be deployed on a live Federalist preview branch so that we can show them off in demos! (if you don't have time for this, I or Amir can take care of it)

**Comment by line47** [comment]
These are really great @austinhernandez ❤️ !
I like how the USWDS does their content where it is information about how it should be thought about and used.
for example, https://designsystem.digital.gov/page-templates/landing/

```
Hero callout:
Call attention to a current priority
Support the callout with some short explanatory text. You don't need more than a couple of sentences.

Learn about what we do
```

**Comment by wslack** [comment]
Next steps:
- Austin is going to deliver 
   - a sketch file with all of the palettes
   - a PNG/PDF with all of the templates together (for those without sketch to see the final work product)
   - all of the hex codes that are components of the palletes
   - documentation for the docs site (this is done)

- Will still needs to
   - figure out where these pallets will live with @line47's advice
   - deploy live previews of all of the options (thereby also uploading the images) akin to the [original example](https://federalist-proxy.app.cloud.gov/preview/18f/uswds-jekyll/sw-color-palette/)
   - enact the documentation created by Austin and Kate, adding a piece about how to technically choose a particular theme

**Comment by austinhernandez** [comment]
## Fresh and Friendly

Range one:
167F91
6ECBDB
D0F1F7

Highlight:
302A26
C7532C
F2DED5

Range two alt:
364173
4A70D9
E1E6FA

**Comment by austinhernandez** [comment]
## Cool Earth Mint

Range one:
11304F
2F6794
79BCF2
F5FBFF

Range two:
178800
80CC7E
E8FAE6

Range two alt:
4A4034
C7A97B
EDE4D5

![cool earth mint 2](https://user-images.githubusercontent.com/23194720/38116406-e9cf8314-337d-11e8-96cf-36648446703e.png)

![cool earth mint 1](https://user-images.githubusercontent.com/23194720/38116410-ecbf3c5e-337d-11e8-827d-f88ddf2725cf.png)

**Comment by austinhernandez** [comment]
## Americana Light

Range one:
0C4D82
3D75C2
91ADD9
DFE7F5

Range two:
AB3A3A
F28F88
F7DDDA

![americana light 2](https://user-images.githubusercontent.com/23194720/38116841-f0d7c30e-337f-11e8-9900-da6a29abb88f.png)

![americana light 1](https://user-images.githubusercontent.com/23194720/38116842-f0e58fd4-337f-11e8-8b6b-79a1c625ebad.png)

**Comment by austinhernandez** [comment]
## Americana Muted

Range one:
631212
AB3A3A
F7E1D5
F7F7F3

Range one alt:
294C69
2F6794
ADD1F0
F5FBFF

Range two:
292A2B
8C9196
D5D8DB

![americana muted 1](https://user-images.githubusercontent.com/23194720/38117247-f3645144-3381-11e8-9d1c-0e4b17329bd2.png)

![americana muted 2](https://user-images.githubusercontent.com/23194720/38117248-f371d09e-3381-11e8-8053-3ed9e385f9d8.png)

![americana muted 3](https://user-images.githubusercontent.com/23194720/38117249-f37fd1b2-3381-11e8-8324-233149f8bd30.png)

**Comment by austinhernandez** [comment]
Next steps and follow up UX work documented on #153

**Comment by wslack** [comment]
I completed one example implementation here: https://federalist-proxy.app.cloud.gov/preview/18f/federalist-uswds-template/palette-experiments/

Reflections:

- Really hard to understand which fields in theme.yml modify which components. It feels like a CSS override of the USWDS values would be much easier than setting so many fields manually.
- Uncommenting the entire file was more annoying than I expected.
- Hard to understand how to replace hero images; the uswds-jekyll documentation isn't super clear
- Color screenshots don't have enough information to inform how menu drop downs should work, color wise.
- We need to provide or point to a tool to try out how different colors work together using template HTML code, a la the markdown helper. Waiting for builds is too slow.

**Comment by wslack** [comment]
Notes from retro

- Images are varying sizes and widths.
- Colors are not named
- We don't know how USWDS colors work
- Theme work tied back to the USWDS color revamp
- Colors fewer than the 5-list
- We could connect all of these to colors names like "light-blue-50" if we want
