### ISSUE TITLE
Add footer variations for slim and big

### ISSUE THREAD

**Issue by line47** [18F/uswds-jekyll#53]
**Issue description:**
Currently we have the option of setting the header type in the `header.yml` file. I think it would be nice to be able to set the footer type as well between `slim`, `medium`, and `big` in the `footer.yml file`. At the moment the default footer is medium. 

You can see the footer code here:
- [slim footer](https://components.standards.usa.gov/components/detail/footer--slim.html)
- [medium footer](https://components.standards.usa.gov/components/detail/footer--default.html)
- [big footer](https://components.standards.usa.gov/components/detail/footer--big.html)

The slim footer would be easier to implement while the big footer would need some thought around how to set up the topic links in the footer.

**Comment by jcastle** [comment]
@line47, this looks good.  Maybe add contact info in case there are questions or comments beyond what could be handled in the issue.

**Comment by line47** [comment]
Thanks @jcastle - I left the contact info out on purpose as the contact info is optional and I'd prefer to track questions/answers in a GitHub thread. Does that sound OK to you?

**Comment by jcastle** [comment]
👍

Sent from my iPhone

On Mar 2, 2018, at 9:31 AM, Scott Weber <notifications@github.com> wrote:

Thanks @jcastle <https://github.com/jcastle> - I left the contact info out
on purpose as the contact info is optional and I'd prefer to track
questions/answers in a GitHub thread. Does that sound OK to you?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/18F/uswds-jekyll/issues/53#issuecomment-369935880>, or mute
the thread

**Comment by Scotchester** [comment]
I'm looking to contribute to some of my government colleagues' work for Hacktoberfest. I'll take this on!

**Comment by line47** [comment]
Amazing, thanks @Scotchester 💃
