### ISSUE TITLE
Unable to use uswds-jekyll with GitHub pages

### ISSUE THREAD

**Issue by jordangov** [18F/uswds-jekyll#85]
I was attempting to use this theme for a site to be hosted on GitHub pages, but it looks like it won't build because this theme isn't on GitHub's supported list. Any chance we can contact GitHub and get it added?

Here is the build failure email I received from GitHub:

> The page build completed successfully, but returned the following warning for the `gh-pages` branch:
> 
> You are attempting to use a Jekyll theme, "uswds-jekyll", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

**Comment by hursey013** [comment]
Thanks @jordangov for reporting this - I actually tried to do the same thing recently and had similar results.

I found a couple of issues that are preventing this from working on Github Pages. The first is the inclusion of a `jekyll_pages_api_search` call being included in one of the includes here: https://github.com/18F/uswds-jekyll/blob/master/_includes/scripts.html#L27

Since the plugin is never installed due to Github's plugin whitelisting, this fails. Need to figure out a way to make this more of a conditional thing.

The other issue, is that there is a README.md being included in the assets/uswds directory, and there is some text in there that is causing Jekyll to throw and error. The line in question has to do with fractal:

`Components that reference other components use a Fractal-specific {% render %} tag that will either need to be implemented in other environments or replaced with the appropriate {% include %} tags.`

So I think the easiest solution for that is maybe to just remove the .md files, or at least that one specifically.

I'll try and put together a PR to address both of these things. cc @line47

**Comment by jordangov** [comment]
Thanks! I was running into both of those issues trying to build locally with the gh-pages gem as well.

**Comment by line47** [comment]
Thanks for taking a look @jordangov and @hursey013 🎉  

This issue was brought up regarding including the U.S. Web Design Standards files https://github.com/18F/uswds-jekyll/issues/93

**Comment by downeym** [comment]
Thanks in advance @hursey013 ... I also ran into the same problem with GH pages today. :-)

**Comment by line47** [comment]
@downeym and @jordangov take a look at the GitHub pages testing I was doing recently...

Repo - https://github.com/line47/testingsearch.github.io
Preview - http://line47.com/testingsearch.github.io/

**Comment by jordangov** [comment]
Hmm, but this doesn't use the `gh-pages` gem... should it? I had issues trying to build when both were included.

**Comment by line47** [comment]
@jordangov - just added the `gem github-pages` and the build seemed to work fine...
https://github.com/line47/testingsearch.github.io/blob/master/Gemfile

**Comment by hursey013** [comment]
@jordangov I'm just running a few more tests locally and then we'll merge this in, but in the meantime if you want to test out setting `remote_theme: 18f/uswds-jekyll@bh-conditional-search` in your _config.yml you should be able to see if your build works on github pages.

**Comment by downeym** [comment]
Build is working here, AFAICT. Thanks!

**Comment by hursey013** [comment]
Confirmed to be working with Github Page and `jekyll-remote-theme`.

**Comment by jordangov** [comment]
Sorry I didn't get back to this! We ended up deploying to S3 anyway as we're going to need to do a couple other things that GH pages can't handle. That said, we did use the USWDS Jekyll theme! Check it out: www.code.mil
